### PR TITLE
fixing cache system for AMD devices

### LINKED ISSUE #242: Cache issue related to AMD devices
The cache system crashes with AMD devices.

see for more details:
- https://github.com/clEsperanto/pyclesperanto/issues/134

### PR DESCRIPTION
**Pull request by StRigaud**
closes #242 
closes https://github.com/clEsperanto/pyclesperanto/issues/134

### CODE REVIEW

File: clic/src/openclbackend.cpp [hunk 1]
```diff
@@ -997,7 +997,7 @@ static auto
 buildProgram(const Device::Pointer & device, const cl_program & program) -> void
 {
   auto   opencl_device = std::dynamic_pointer_cast<const OpenCLDevice>(device);
-  cl_int buildStatus = clBuildProgram(program, 1, &opencl_device->getCLDevice(), "-w", nullptr, nullptr);
+  cl_int buildStatus = clBuildProgram(program, 1, &opencl_device->getCLDevice(), "-w -cl-mad-enable", nullptr, nullptr);
```
Comment (haesleinhuepf) [inline clic/src/openclbackend.cpp:1000]:
```suggestion
  cl_int buildStatus = clBuildProgram(program, 1, &opencl_device->getCLDevice(), "-w", nullptr, nullptr);
```
That was an unintended change

File: tests/core/test_array.cpp [hunk 2]
```diff
@@ -40,7 +40,7 @@ TEST_P(TestArray, typeDataMemory)
 {
   std::string param = GetParam();
   cle::BackendManager::getInstance().setBackend(param);
-  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
+  auto device = cle::BackendManager::getInstance().getBackend().getDevice("gfx1035", "all");
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:43]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_array.cpp [hunk 3]
```diff
@@ -57,7 +57,7 @@ TEST_P(TestArray, allocateWrite)
...
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:60]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_array.cpp [hunk 4]
```diff
@@ -85,7 +85,7 @@ TEST_P(TestArray, readWrite)
...
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:88]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_array.cpp [hunk 5]
```diff
@@ -183,7 +183,7 @@ TEST_P(TestArray, regionOperation)
...
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:186]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_array.cpp [hunk 6]
```diff
@@ -258,7 +258,7 @@ TEST_P(TestArray, throwErrors)
...
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:261]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_execute.cpp [hunk 7]
```diff
@@ -11,7 +11,7 @@ TEST_P(TestExecution, parameterType)
 {
   std::string param = GetParam();
   cle::BackendManager::getInstance().setBackend(param);
-  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
+  auto device = cle::BackendManager::getInstance().getBackend().getDevice("gfx1035", "all");
```
Comment (haesleinhuepf) [inline tests/core/test_execute.cpp:14]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_execute.cpp [hunk 8]
```diff
@@ -34,7 +34,7 @@ TEST_P(TestExecution, parameterList)
...
```
Comment (haesleinhuepf) [inline tests/core/test_execute.cpp:37]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/core/test_execute.cpp [hunk 9]
```diff
@@ -57,7 +57,7 @@ TEST_P(TestExecution, rangeArray)
...
```
Comment (haesleinhuepf) [inline tests/core/test_execute.cpp:60]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

File: tests/tier7/test_voronoi_otsu_labeling.cpp [hunk 10]
```diff
@@ -2,6 +2,7 @@
 
 #include <array>
 #include <gtest/gtest.h>
+#include <stdio.h>
```
Comment (haesleinhuepf) [inline tests/tier7/test_voronoi_otsu_labeling.cpp:5]:
```suggestion

```

File: tests/tier7/test_voronoi_otsu_labeling.cpp [hunk 11]
```diff
@@ -25,12 +26,18 @@ TEST_P(TestVoronoiOtsuLabeling, execute)
...
+  std::cout << device << std::endl;
+  std::cout << device->getInfo() << std::endl;
+
   device->setWaitToFinish(true);
 
   auto gpu_input = cle::Array::create(7, 7, 3, 3, cle::dType::FLOAT, cle::mType::BUFFER, device);
   gpu_input->write(input.data());
 
+  std::cout << gpu_input << std::endl;
+
```
Comment (haesleinhuepf) [inline tests/tier7/test_voronoi_otsu_labeling.cpp:40]:
```suggestion
```

File: tests/core/test_array.cpp [hunk 12]
```diff
@@ -10,7 +10,7 @@ TEST_P(TestArray, allocate)
...
```
Comment (haesleinhuepf) [inline tests/core/test_array.cpp:13]:
```suggestion
  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
```

**Comment by haesleinhuepf** [comment]
🎉
